baseurl = "https://doks.osumontreal.ca/"
canonifyURLs = false
disableAliases = false
disableHugoGeneratorInject = false
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10
theme = "doks"

# add redirects/headers
[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS", "SITEMAP"]


# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"
    tabWidth = 4

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  contributor = "contributors"

[permalinks]
  blog = "/blog/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "themes/doks/node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "themes/doks/node_modules/katex"
    target = "assets/js/vendor/katex"
    [[module.mounts]]
    source = "themes/doks/node_modules/katex/dist"
    target = "assets/scss/katex"
  [[module.mounts]]
    source = "themes/doks/node_modules/katex/dist/fonts"
    target = "static/fonts"
  [[module.mounts]]
    source = "themes/doks/node_modules/mermaid"
    target = "assets/js/vendor/mermaid"
  [[module.mounts]]
    source = "themes/doks/node_modules/bootstrap"
    target = "assets/bootstrap"
  [[module.mounts]]
    source = "themes/doks/node_modules/lazysizes"
    target = "assets/js/vendor/lazysizes"
  [[module.mounts]]
    source = "themes/doks/node_modules/instant.page"
    target = "assets/js/vendor/instant.page"
  [[module.mounts]]
    source = "themes/doks/node_modules/highlight.js"
    target = "assets/js/vendor/highlight.js"
  [[module.mounts]]
    source = "themes/doks/node_modules/clipboard/dist"
    target = "assets/js/vendor/clipboard"